#include "../Shape3D/Capsule.hpp"
#include "../Shape3D/Sphere.hpp"
#include "../Shape3D/Plane.hpp"
#include "../Shape3D/Point.hpp"
#include "../Shape3D/Triangle.hpp"
#include "../Shape3D/Box.hpp"
#include "../Shape3D/Cone.hpp"
#include "../Shape3D/AlignedBoxes.hpp"
#include "../Shape3D/AlignedCapsules.hpp"
#include "../Shape3D/AlignedTriangles.hpp"
 